apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kbin.labels" . | nindent 4 }}
  name: {{ include "kbin.fullname" . }}-caddy
  annotations:
    {{- with (default .Values.deploymentAnnotations .Values.php.deploymentAnnotation) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.caddy.service.port | default 80 }}
    name: web
  selector:
    {{- include "kbin.caddy.selectorLabels" . | nindent 4 }}
  type: {{ .Values.caddy.service.type | default "ClusterIP" }}