monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            # dump stack traces
            formatter: debug_logger
            include_stacktraces: true
        nested:
            type: stream
            path: "php://stderr"
            level: error
            # dump stack traces
            formatter: debug_logger
            include_stacktraces: true
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
