parameters:
  LOG_LEVEL: '%env(SYMFONY_LOGLEVEL)%'
  S3_KEY: '%env(S3_KEY)%'
  S3_SECRET: '%env(S3_SECRET)%'
  S3_BUCKET: '%env(S3_BUCKET)%'
  S3_REGION: '%env(S3_REGION)%'
  S3_VERSION: '%env(S3_VERSION)%'
  S3_ENDPOINT: '%env(S3_ENDPOINT)%'
  S3_USE_PATH_STYLE_ENDPOINT: '%env(bool:S3_USE_PATH_STYLE_ENDPOINT)%'

  amazon.s3.key: '%env(S3_KEY)%'
  amazon.s3.secret: '%env(S3_SECRET)%'
  amazon.s3.bucket: '%env(S3_BUCKET)%'
  amazon.s3.region: '%env(S3_REGION)%'
  amazon.s3.version: '%env(S3_VERSION)%'
  amazon.s3.endpoint: '%env(S3_ENDPOINT)%'
  amazon.s3.use_path_endpoint: '%env(bool:S3_USE_PATH_STYLE_ENDPOINT)%'


framework:
  # trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_proxies: '127.0.0.1,REMOTE_ADDR'
  trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']


services:
  kbin.s3_client:
    class: Aws\S3\S3Client
    arguments:
      - version: '%S3_VERSION%'
        region: '%S3_REGION%'
        credentials:
          key: '%S3_KEY%'
          secret: '%S3_SECRET%'
        endpoint: '%S3_ENDPOINT%'
        use_path_style_endpoint: '%S3_USE_PATH_STYLE_ENDPOINT%'
  debug_logger:
    class: Monolog\Formatter\LineFormatter
    calls:
      - [includeStackTraces]