apiVersion: v1
kind: Secret
metadata:
  name: kbin-admin
type: Opaque
data:
{{/*
Get mercure jwt secret - use existing secret 
*/}}
{{- $kbinAdmin := (lookup "v1" "Secret" .Release.Namespace "kbin-admin") }}
{{- $kbinAdminData := (get $kbinAdmin "data") | default dict }}
{{- $kbinAdminSecret := (get $kbinAdminData "kbinpassword") | default (randAlphaNum 32 | b64enc) }}
  kbinpassword: {{ $kbinAdminSecret | quote }}
  kbinusername: {{ .Values.adminUsername | b64enc | quote }}