apiVersion: v1
kind: Secret
metadata:
  name: kbin-mercure
type: Opaque
data:
{{/*
Get mercure jwt secret - use existing secret 
*/}}
{{- $mercureSecObj := (lookup "v1" "Secret" .Release.Namespace "kbin-mercure") }}
{{- $mercureSecData := (get $mercureSecObj "data") | default dict }}
{{- $mercureSecret := (get $mercureSecData "mercure-jwt-secret") | default (randAlphaNum 32 | b64enc) }}
  mercure-jwt-secret: {{ $mercureSecret | quote }}