{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kbin-minio
type: Opaque
data:
{{/*
Get minio creds - use existing if it exists
*/}}
{{- $minioSecObj := (lookup "v1" "Secret" .Release.Namespace "kbin-minio") }}
{{- $minioSecData := (get $minioSecObj "data") | default dict }}
{{- $miniouser := (get $minioSecData "root-user") | default (randAlphaNum 12 | b64enc) }}
{{- $miniopass := (get $minioSecData "root-password") | default (randAlphaNum 32 | b64enc) }}
  root-user: {{ $miniouser | quote }}
  root-password: {{ $miniopass | quote }}
{{ end -}}