apiVersion: v1
kind: Secret
metadata:
  name: kbin-postgres
type: Opaque
data:
{{/*
Get postgres secret - use existing secret if it exists
*/}}
{{- $postgresSecObj := (lookup "v1" "Secret" .Release.Namespace "kbin-postgres") }}
{{- $postgresSecData := (get $postgresSecObj "data") | default dict }}
{{- $postgresSecret := (get $postgresSecData "password") | default (randAlphaNum 32 | b64enc) }}
  postgres-password: {{ $postgresSecret | quote }}
  password: {{ $postgresSecret | quote }}