apiVersion: v1
kind: Secret
metadata:
  name: kbin-rabbitmq-password
type: Opaque
data:
{{/*
Get redis secret - use existing secret if it exists
*/}}
{{- $rabbitSecObj := (lookup "v1" "Secret" .Release.Namespace "kbin-rabbitmq-password") }}
{{- $rabbitSecData := (get $rabbitSecObj "data") | default dict }}
{{- $rabbitSecret := (get $rabbitSecData "rabbitmq-password") | default (randAlphaNum 32 | b64enc) }}
  rabbitmq-password: {{ $rabbitSecret | quote }}