apiVersion: v1
kind: Secret
metadata:
  name: kbin-redis
type: Opaque
data:
{{/*
Get redis secret. use existing secret if it exists
*/}}
{{- $redisSecObj := (lookup "v1" "Secret" .Release.Namespace "kbin-redis") }}
{{- $redisSecData := (get $redisSecObj "data") | default dict }}
{{- $redisSecret := (get $redisSecData "password") | default (randAlphaNum 32 | b64enc) }}
  password: {{ $redisSecret | quote }}